#!/usr/bin/env bash
# Generate -480/-800 responsive variants for every public/images .webp and push
# them to R2 next to the originals (targeted `aws s3 cp` per object — NEVER
# `s3 sync`, cf CLAUDE.md). Idempotent: existing R2 variants are overwritten
# with freshly derived ones, originals are never touched.
#
# Usage:  set -a; source ~/.claude/secrets.env; set +a
#         ./scripts/gen-image-variants.sh [--dry-run]
set -euo pipefail
cd "$(dirname "$0")/.."

DRY_RUN="${1:-}"
OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

command -v magick >/dev/null || { echo "magick (ImageMagick) requis" >&2; exit 1; }
[ -n "${R2_ACCESS_KEY_ID:-}" ] || { echo "R2_* absents — sourcer ~/.claude/secrets.env" >&2; exit 1; }

find public/images -name '*.webp' ! -name '*-480.webp' ! -name '*-800.webp' | while read -r f; do
  rel="${f#public/}"                      # images/services/traefik.webp
  base="${rel%.webp}"
  for w in 480 800; do
    out="$OUT/${base}-${w}.webp"
    mkdir -p "$(dirname "$out")"
    magick "$f" -resize "${w}x>" -quality 80 "$out"
    if [ "$DRY_RUN" = "--dry-run" ]; then
      echo "DRY: s3://pixelium-assets/${base}-${w}.webp ($(du -h "$out" | cut -f1))"
    else
      AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" AWS_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" \
        aws s3 cp "$out" "s3://pixelium-assets/${base}-${w}.webp" \
        --endpoint-url "$R2_ENDPOINT" --region auto --no-progress
    fi
  done
done

# Regenerate the dimensions map so assetSrcset() emits an honest `Nw` for the
# original AND Screenshot/Carousel can set width/height (reserve space, no CLS).
# Local file — refreshed unless --dry-run.
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo "DRY: régénérerait src/image-dims.ts ([largeur, hauteur] réelles des originaux)"
else
  MAP="src/image-dims.ts"
  {
    echo "// AUTO-GENERATED by scripts/gen-image-variants.sh — do not edit by hand."
    echo "// Real pixel [width, height] of image originals. Used by assetSrcset() for an"
    echo "// honest \`Nw\` descriptor AND by Screenshot/Carousel to set width/height (reserve"
    echo "// space, kill CLS). Regenerate after adding/replacing images: ./scripts/gen-image-variants.sh"
    echo "export const IMAGE_DIMS: Record<string, [number, number]> = {"
    find public/images -name '*.webp' ! -name '*-480.webp' ! -name '*-800.webp' | sort | while read -r f; do
      rel="${f#public/}"
      dims="$(magick identify -format '%w %h' "$f")"; w="${dims% *}"; h="${dims#* }"
      echo "  \"/${rel}\": [${w}, ${h}],"
    done
    echo "};"
  } > "$MAP"
  echo "wrote $MAP"
fi
echo "done."
