/** Base URL for image assets hosted on Cloudflare R2 */
export const ASSETS_BASE = 'https://assets.pixelium.win';

/** Prefix a local image path with the R2 base URL */
export function assetUrl(path: string): string {
  return `${ASSETS_BASE}${path.startsWith('/') ? '' : '/'}${path}`;
}

/**
 * Responsive srcset for an R2 .webp asset, by naming convention: -480 and -800
 * variants live next to the original (`x.webp` → `x-480.webp`, `x-800.webp`),
 * pre-generated by scripts/gen-image-variants.sh and pushed to R2 alongside it.
 * The original stays the largest candidate. Non-.webp paths get no srcset.
 */
export function assetSrcset(path: string): string | undefined {
  if (!path.endsWith('.webp')) return undefined;
  const base = assetUrl(path).slice(0, -'.webp'.length);
  return `${base}-480.webp 480w, ${base}-800.webp 800w, ${base}.webp 1200w`;
}
