// AUTO-GENERATED by scripts/gen-image-variants.sh — do not edit by hand.
// Real pixel widths of image originals, so assetSrcset() declares an honest
// `Nw` for the original candidate (widths vary 1200..2944px). Regenerate after
// adding/replacing images:  ./scripts/gen-image-variants.sh
export const IMAGE_WIDTHS: Record<string, number> = {
  "/images/homepage-dashboard.webp": 2944,
  "/images/htb-dashboard.webp": 1200,
  "/images/immich-gallery-1.webp": 1920,
  "/images/immich-gallery-2.webp": 1920,
  "/images/monitoring/beszel.webp": 1200,
  "/images/monitoring/patchmon.webp": 1200,
  "/images/monitoring/pentagi.webp": 1200,
  "/images/monitoring/victoriametrics.webp": 1200,
  "/images/monitoring/wazuh2.webp": 1200,
  "/images/monitoring/wazuh.webp": 1200,
  "/images/neofetch-terre2.webp": 1316,
  "/images/pve1.webp": 1920,
  "/images/pve2-dashboard.webp": 1796,
  "/images/pve2.webp": 1920,
  "/images/pve3.webp": 1200,
  "/images/services/authentik.webp": 1200,
  "/images/services/bytestash.webp": 1200,
  "/images/services/immich.webp": 1200,
  "/images/services/joplin.webp": 1200,
  "/images/services/netboot.webp": 1200,
  "/images/services/netbox.webp": 1200,
  "/images/services/omv.webp": 1200,
  "/images/services/semaphore.webp": 1200,
  "/images/services/technitium.webp": 1200,
  "/images/services/traefik.webp": 1200,
};
