// AUTO-GENERATED by scripts/gen-image-variants.sh — do not edit by hand.
// Real pixel [width, height] of image originals. Used by assetSrcset() for an
// honest `Nw` descriptor AND by Screenshot/Carousel to set width/height (reserve
// space, kill CLS). Regenerate after adding/replacing images: ./scripts/gen-image-variants.sh
export const IMAGE_DIMS: Record<string, [number, number]> = {
  "/images/homepage-dashboard.webp": [2944, 2049],
  "/images/htb-dashboard.webp": [1200, 646],
  "/images/immich-gallery-1.webp": [1920, 2022],
  "/images/immich-gallery-2.webp": [1920, 2022],
  "/images/monitoring/beszel.webp": [1200, 703],
  "/images/monitoring/patchmon.webp": [1200, 703],
  "/images/monitoring/pentagi.webp": [1200, 630],
  "/images/monitoring/victoriametrics.webp": [1200, 703],
  "/images/monitoring/wazuh2.webp": [1200, 703],
  "/images/monitoring/wazuh.webp": [1200, 703],
  "/images/neofetch-terre2.webp": [1316, 1096],
  "/images/pve1.webp": [1920, 1124],
  "/images/pve2-dashboard.webp": [1796, 674],
  "/images/pve2.webp": [1920, 1124],
  "/images/pve3.webp": [1200, 703],
  "/images/services/authentik.webp": [1200, 703],
  "/images/services/bytestash.webp": [1200, 703],
  "/images/services/immich.webp": [1200, 703],
  "/images/services/joplin.webp": [1200, 703],
  "/images/services/netboot.webp": [1200, 703],
  "/images/services/netbox.webp": [1200, 703],
  "/images/services/omv.webp": [1200, 703],
  "/images/services/semaphore.webp": [1200, 703],
  "/images/services/technitium.webp": [1200, 703],
  "/images/services/traefik.webp": [1200, 703],
};
